name = "gleam_json"
version = "3.1.0"
gleam = ">= 1.13.0"

licences = ["Apache-2.0"]
description = "Work with JSON in Gleam (macabre python-target fork of gleam_json)"

repository = { type = "github", user = "dusty-phillips", repo = "macabre_json" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = { git = "git@github.com:dusty-phillips/macabre_stdlib.git", ref = "main" }
macabre_stdlib = { git = "git@github.com:dusty-phillips/macabre_stdlib.git", ref = "main" }

[dev-dependencies]
gleeunit = { git = "git@github.com:dusty-phillips/macabre_gleeunit.git", ref = "main" }
